---
title: " "
output: pdf_document
---

# Discussion

**Abundance and Biodiversity Indices**

Wetlands are valuable ecosystems for society [@clarksonWetlandEcosystemServices2013]. Unfortunately, there has been global wetland degradation with about half of the global wetlands being lost to accommodate for agricultural practices and urbanisation. The loss of wetlands has a negative impact on biodiversity, human well-being and has negative long-term impacts on economies [@clarksonWetlandEcosystemServices2013]. This has given rise to many wetland conservation projects, both locally (Working for Wetlands project) and globally (RAMSAR and AEWA).

Out of the three waterbird attributes investigated in this study (migratory status, nest site and number of foraging sites used), the migratory status seemed to be the most likely to affect population declines, as proportionally more migratory waterbirds displayed declining trends (50%) compared to resident waterbirds (14.6%). The other attributes investigated provided no significant evidence to suggest that they are drivers for population change among the waterbirds in Barberspan. 

The higher rate of decline within the migratory waterbirds agrees with similar reports on waterbirds in Southern Africa. A study on migratory waterbirds in South Africa reported that 11 of the 16 palearctic migrants investigated experienced negative trends from 2005-2009 [@barshepIdentifyingEcologicalLifehistory2017]. A paper analysing palearctic migrants in Sandwich Harbour and Walvis Bay, Namibia, reported similar findings; four of the 12 palearctic migrants studied experienced declines while only one species experienced an increasing trend (Common Whimbrel) from 1990-2013 [@simmonsDeclinesMigrantShorebird2015]. Further studies show that Palearctic-Afrotropical migratory waterbirds are experiencing declines in abundance globally [@kirbyKeyConservationIssues2008; @deniauFlywaysHellEmpirical2022].

The Simpson index displays some evidence that both the migratory and the resident waterbirds of Barberspan are becoming less even over time. This means that there are some waterbirds that are dominating while other species are leaving Barberspan. Investigating the SSM output on the individual migratory waterbirds (Appendix B) we see 6 out of the 14 migratory waterbirds make up over 85% of the total counts for all migratory waterbirds at Barberspan used in this study. These are the Little Stint, Ruff, Curlew Sandpiper, White-winged tern, Whiskered tern and Common Ringed Plover. These 6 waterbirds all displayed fairly positive trends up until year 2013 - 2015, while the rest of the migratory waterbirds displayed decreasing trends or no discernible trend at all. This leads to an increasingly uneven community of waterbirds over time and a decrease in effective number of species over time. After the declining period between the year 2013 and 2015, only the Curlew Sandpiper recovered and started displaying a positive trend again. This leads to further unevenness in the community and a further decrease in the effective number of migratory waterbirds in Barberspan. We see these aspects reflected in the Simpson's and exponentiated Shannon's index. The Shannon's index displays a decrease in effective number of species over time until it reaches an effective number of approximately four to six migratory waterbirds in Barberspan from 2013 onward. Similarly, the Simpson's index displays a decrease in evenness over time until it reaches a value of 0.6 for the winter counts and 0.66 for the summer counts in 2018. 
It is interesting to note that the migratory waterbirds mostly experience a higher effective number of species in winter compared to summer, even though there are significantly less migratory waterbirds at Barberspan during the winter. This result is due to the higher degrees of evenness displayed in winter than summer for the migratory waterbirds. There are less migratory birds in winter but higher evenness and therefore higher a effective number of species. Whereas, in summer there are the 6 dominant waterbirds present, as mentioned earlier, which leads to a lower number of effective species.

High measures of unevenness among migratory waterbird species were also presented in a study conducted in the wetlands of Northeastern Algeria. @aliDiversityPatternsSeasonal2016, discovered a high dominance in Eurasian Coots in the wetland studied. The Eurasian Coots made up about 53% of the 39 migratory waterbird species found in the wetland. similarly, A study conducted in a South African riverine habitat, the Shamvura stretch of the Okavango River, also found high levels of dominance among the waterbirds present in the wetland [@kopijSeasonalChangesDiversity2018]. In this study there were 6 resident waterbirds out of the 84 recorded waterbirds that were classified as dominant: African reed cormorant, African openbill, cattle egret, wattled lapwing, African darter and white-faced duck. 

Among the waterbirds in Barberspan it was also found that resident species were most dominant. The Egyptian Goose and the Red-Knobbed Coot made up 70% of all waterbird counts at Barberspan with the Red-Knobbed Coot being most dominant making up 58% of all counts. The effective number of resident species stayed relatively constant over time, for summer and winter, compared to the migratory birds. Residents displayed a exponentiated Shannon's index of around four to ten regardless of the season. This makes sense as these species do not migrate and so there would be less fluctuation in their abundance compared to the migratory waterbirds. 

The outcome of this report is a first step in displaying what can be done using the CWAC dataset. The aspects of biodiversity to monitor were selected based on analysing what needs to be monitored, who needs to monitor it and why it needs to be monitored, thus following the instruction of @yoccozMonitoringBiologicalDiversity2001. The individual indices were selected based on best practices in quantifying biodiversity [@bucklandMonitoringChangeBiodiversity2005; @bucklandHowShouldRegional2012]. The three indices used in conjunction with one another provide a good overview of the waterbird and wetland state. For example, if the modified LPI displays alarming negative percentage changes for a year or two the user can use the other indices and time series plots to investigate. One could check the exponentiated Shannon’s index to see if the effective number of species types has decreased or has all types of species been leaving the wetland at the same rate. One could also check the Simpson’s index to identify if there are any dominant species that are using up resources of other species and driving them away as a result. If the Simpson’s index displays strong unevenness, the user can then analyse the individual time series plots to identify which species are increasing and which are decreasing. Knowing exactly which waterbird species are decreasing and which are increasing provides valuable insight into which aspects of the wetland may be a problem. For example, increases in Great Crested Grebe can be indicative of increased eutrophication levels [@amatWaterbirdsBioindicatorsEnvironmental2010] and decreases in Red-Knobbed Coots can be indicative of increased siltation rates in the water and soil of a wetland [@amatWaterbirdsBioindicatorsEnvironmental2010].

**The State-Space Model**

The state-space model used in a Bayesian context has the potential to quantify uncertainty more thoroughly than the popular methods currently used. Indices such as the LPI, Shannon's index and Simpson's index are most commonly presented with confidence intervals created by bootstrap sampling [@mcraeDiversityWeightedLivingPlanet2017; @collenMonitoringChangeVertebrate2009; @lohLivingPlanetIndex2005; @fontanaHowManageUrban2011; @bucklandMonitoringChangeBiodiversity2005]. These confidence intervals only include uncertainty around the trends, however, the population sizes themselves are also uncertain. Using the SSM in a Bayesian context, as performed in this study, provides a platform to quantify uncertainty around population sizes that can consequently be used to establish uncertainty around biodiversity indices calculated using those population sizes such as the LPI, Shannon's and Simpson's index. 

The index outputs were subject to fairly high levels of uncertainty due to the time series being relatively short. Furthermore, we are trying to estimate the observation process independently for every species which leads to high uncertainty around the population sizes. The state-space model models each individual waterbird species with its own observation error, thus when performing operations between the posterior output of individual species we experience an accumulative effect on the error values. The state-space model should ideally be altered to incorporate an observation error per counting session instead of per species. This would be a more realistic model and would, theoretically, produce smaller, and more realistic, credible intervals.

Further benefits of the state-space model is its ability to provide better approximations of the true population based on the bird counts [@auger-metheGuideStatespaceModeling2021]. Popular indices such as the Living Planet Index (LPI) and the Australian Threatened Bird Index, use General Additive Models (GAMS) based on bird counts to calculate their indices [@mcraeDiversityWeightedLivingPlanet2017; @bayraktarovThreatenedSpeciesIndex2020]. The trends calculated using GAMS are more affected by sampling variation compared to SSMs, which separate the sampling variation from the latent variation.

The SSM can also be altered to incorporate covariates into the analysis of the CWAC data. For example, we see that the effective number of waterbird species in Barberspan are decreasing over time, this is displayed in the exponentiated Shannon's index. Further investigation could be made to identify which factors are affecting the fluctuation of waterbirds in South African wetlands. To aid such an investigation, various auxiliary variables can be monitored and/or obtained such as water level, temperature, climate, foot traffic frequency, etc. These variables could be incorporated into the SSM for a deeper insight into how these variables affect waterbird population fluctuation and, consequently, the state of the wetland. No covariates were used in this dissertation as it was out of the scope of the research. Furthermore, time constraints inhibited obtaining auxiliary datasets for Barberspan. 

The SSM can be altered to incorporate various variables into the model by using a multivariate auto-regressive state-space model (MARSS). A similar approach has been taken by @elghafghufUsingStatespaceModels2018 to model the abundance of sea lice on Atlantic salmon over time. Incorporating temperature (or similar climate change indicators) as a covariate in the analysis of the CWAC data could be beneficial, as an overwhelming number of studies state that climate change is likely the main driver in the declining waterbird populations [@macleanEffectsClimateChange2007; @kirbyKeyConservationIssues2008; @pavon-jordanClimatedrivenChangesWinter2015]. As a start, one could use a MARSS model and incorporate average seasonal temperature as a covariate in the time series analysis of the CWAC data. This follows a similar approach followed by @oedekovenAttributingChangesDistribution2017 in attributing changes in the distribution of species abundance of British breeding birds. 

Using population estimates produced by an SSM (calculated in a Bayesian framework) to calculate biodiversity indices is a relatively new concept and literature is limited regarding this methodology. This dissertation provides valuable insight into the limitations and potential of calculating biodiversity indices in this manner. 

Furthermore, this dissertation has highlighted the many benefits of using state-space models to model population dynamics and using the output to formulate biodiversity indices. SSMs prove to be flexible models that are intuitive to use in a Bayesian framework when modelling population dynamics [@auger-metheGuideStatespaceModeling2021]. Furthermore, using population estimates obtained from SSMs to calculate biodiversity indices produce biodiversity indices that are less affected by sampling variation.

# Conclusion

The CWAC dataset proves to be beneficial in displaying the state of waterbirds and wetlands in South Africa. State-space time series models model both the migrant and resident population dynamics well. Using the modified LPI, exponentiated Shannon's entropy and Simpson's index in conjunction provides good insight into the state of the waterbirds and wetland in question. These three indicators can help conservationists develop more targeted approaches in their efforts to conserve waterbirds and wetlands.

We also find strong potential in the use of state-space models for modelling population dynamics and using the population estimates to calculate biodiversity indices. This method of calculating biodiversity indices provide one with the ability to provide credible intervals around the index. Furthermore, the index is less affected by sampling variation.   



